'use client';

import Link from 'next/link';
import { useLocale } from '@/i18n/useLocale';
import { useTheme } from '@/hooks/useTheme';
import LanguageSelector from '@/components/shared/LanguageSelector';
import Footer from '@/components/shared/Footer';

export default function PolicyPage() {
  const { t } = useLocale();
  const { theme, toggleTheme } = useTheme();

  return (
    <div className="min-h-screen bg-white dark:bg-zinc-950">
      <header className="sticky top-0 z-10 border-b border-zinc-200 dark:border-zinc-800 bg-white/80 dark:bg-zinc-950/80 backdrop-blur-sm px-6 py-3">
        <div className="mx-auto max-w-3xl flex items-center gap-4">
          <Link href="/" className="text-zinc-500 dark:text-zinc-400 hover:text-zinc-700 dark:hover:text-zinc-200 transition-colors">
            {t('common.backToDomains')}
          </Link>
          <h1 className="text-lg font-bold text-zinc-900 dark:text-zinc-100">{t('policy.title')}</h1>
          <div className="ml-auto flex items-center gap-2">
            <LanguageSelector />
            <button
              onClick={toggleTheme}
              className="p-1.5 rounded-md hover:bg-zinc-100 dark:hover:bg-zinc-800 transition-colors text-zinc-500 dark:text-zinc-400"
            >
              {theme === 'dark' ? (
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="5"/><line x1="12" y1="1" x2="12" y2="3"/><line x1="12" y1="21" x2="12" y2="23"/><line x1="4.22" y1="4.22" x2="5.64" y2="5.64"/><line x1="18.36" y1="18.36" x2="19.78" y2="19.78"/><line x1="1" y1="12" x2="3" y2="12"/><line x1="21" y1="12" x2="23" y2="12"/><line x1="4.22" y1="19.78" x2="5.64" y2="18.36"/><line x1="18.36" y1="5.64" x2="19.78" y2="4.22"/></svg>
              ) : (
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z"/></svg>
              )}
            </button>
          </div>
        </div>
      </header>

      <main className="mx-auto max-w-3xl px-6 py-10">
        <div className="prose prose-zinc dark:prose-invert max-w-none prose-headings:text-zinc-900 dark:prose-headings:text-zinc-100 prose-p:text-zinc-700 dark:prose-p:text-zinc-300 prose-li:text-zinc-700 dark:prose-li:text-zinc-300">
          <h1>{t('policy.title')}</h1>

          <h2>{t('policy.aboutTitle')}</h2>
          <p>{t('policy.aboutBody')}</p>

          <h2>{t('policy.disclaimerTitle')}</h2>
          <p>{t('policy.disclaimerBody')}</p>
          <p>{t('policy.disclaimerAccounting')}</p>

          <h2>{t('policy.privacyTitle')}</h2>
          <p>{t('policy.privacyBody')}</p>

          <h2>{t('policy.techTitle')}</h2>
          <ul>
            <li>Next.js (Static Export) + React + TypeScript</li>
            <li>Hosted on GitHub Pages</li>
            <li>Content generated by Claude (Anthropic) and Google Gemini (illustrations)</li>
            <li>KaTeX for mathematical notation</li>
          </ul>

          <h2>{t('policy.licenseTitle')}</h2>
          <p>
            {t('policy.licenseBody')}{' '}
            <a href="https://github.com/kent-tokyo/plactice_math" target="_blank" rel="noopener noreferrer">GitHub</a>
          </p>

          <h2>{t('policy.contactTitle')}</h2>
          <p>
            {t('policy.contactBody')}{' '}
            <a href="https://github.com/kent-tokyo/plactice_math/issues" target="_blank" rel="noopener noreferrer">GitHub Issues</a>
          </p>
        </div>
      </main>
      <Footer />
    </div>
  );
}
