'use client';

import Link from 'next/link';
import { useLocale } from '@/i18n/useLocale';
import { useTheme } from '@/hooks/useTheme';
import Footer from '@/components/shared/Footer';

export default function PolicyPage() {
  const { t } = useLocale();
  const { theme, toggleTheme } = useTheme();

  return (
    <div className="min-h-screen bg-white dark:bg-zinc-950">
      <header className="sticky top-0 z-10 border-b border-zinc-200 dark:border-zinc-800 bg-white/80 dark:bg-zinc-950/80 backdrop-blur-sm px-6 py-3">
        <div className="mx-auto max-w-3xl flex items-center gap-4">
          <Link href="/" className="text-zinc-500 dark:text-zinc-400 hover:text-zinc-700 dark:hover:text-zinc-200 transition-colors">
            ← {t('common.backToDomains')}
          </Link>
          <h1 className="text-lg font-bold text-zinc-900 dark:text-zinc-100">Site Policy</h1>
          <div className="ml-auto">
            <button
              onClick={toggleTheme}
              className="p-1.5 rounded-md hover:bg-zinc-100 dark:hover:bg-zinc-800 transition-colors text-zinc-500 dark:text-zinc-400"
            >
              {theme === 'dark' ? (
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="5"/><line x1="12" y1="1" x2="12" y2="3"/><line x1="12" y1="21" x2="12" y2="23"/><line x1="4.22" y1="4.22" x2="5.64" y2="5.64"/><line x1="18.36" y1="18.36" x2="19.78" y2="19.78"/><line x1="1" y1="12" x2="3" y2="12"/><line x1="21" y1="12" x2="23" y2="12"/><line x1="4.22" y1="19.78" x2="5.64" y2="18.36"/><line x1="18.36" y1="5.64" x2="19.78" y2="4.22"/></svg>
              ) : (
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z"/></svg>
              )}
            </button>
          </div>
        </div>
      </header>

      <main className="mx-auto max-w-3xl px-6 py-10">
        <div className="prose prose-zinc dark:prose-invert max-w-none prose-headings:text-zinc-900 dark:prose-headings:text-zinc-100 prose-p:text-zinc-700 dark:prose-p:text-zinc-300 prose-li:text-zinc-700 dark:prose-li:text-zinc-300">
          <h1>Site Policy / サイトポリシー</h1>

          <h2>About This Site / 本サイトについて</h2>
          <p>
            plactice_math is a free educational web application for learning concepts across multiple domains
            including mathematics, philosophy, AWS, computer science, chemistry, and accounting.
            All learning content is generated by AI (Claude by Anthropic) and reviewed for accuracy.
          </p>
          <p>
            本サイト（plactice_math）は、数学・哲学・AWS・コンピュータサイエンス・化学・会計など複数分野の概念学習を支援する無料のWebアプリケーションです。
            学習コンテンツはAI（Anthropic社のClaude）により生成され、正確性を確認しています。
          </p>

          <h2>Disclaimer / 免責事項</h2>
          <p>
            The content on this site is generated by AI and is intended for educational purposes only.
            While we strive for accuracy, we do not guarantee the correctness, completeness, or timeliness of the information provided.
            Users should verify important information with authoritative sources.
          </p>
          <p>
            本サイトのコンテンツはAIにより生成されたものであり、教育目的でのみ提供されます。
            正確性には努めていますが、情報の正確性・完全性・最新性を保証するものではありません。
            重要な情報は権威ある情報源でご確認ください。
          </p>
          <p>
            For accounting content specifically: explanations are based on Japanese GAAP (J-GAAP) with references to IFRS where applicable.
            This content does not constitute professional accounting or tax advice.
          </p>
          <p>
            特に会計コンテンツについて：説明は日本基準（J-GAAP）を基本とし、必要に応じてIFRSとの差異に言及しています。
            本コンテンツは専門的な会計・税務アドバイスを構成するものではありません。
          </p>

          <h2>Privacy / プライバシー</h2>
          <p>
            This site does not collect personal information. All learning progress and settings are stored
            locally in your browser (localStorage) and are never transmitted to any server.
          </p>
          <p>
            本サイトは個人情報を収集しません。学習進捗や設定はすべてブラウザのlocalStorageに保存され、
            サーバーに送信されることはありません。
          </p>

          <h2>Technology / 使用技術</h2>
          <ul>
            <li>Next.js (Static Export) + React + TypeScript</li>
            <li>Hosted on GitHub Pages</li>
            <li>Content generated by Claude (Anthropic) and Google Gemini (illustrations)</li>
            <li>KaTeX for mathematical notation</li>
          </ul>

          <h2>License / ライセンス</h2>
          <p>
            The source code is available on <a href="https://github.com/kent-tokyo/plactice_math" target="_blank" rel="noopener noreferrer">GitHub</a>.
            Generated content is provided as-is for educational use.
          </p>

          <h2>Contact / お問い合わせ</h2>
          <p>
            For bug reports or feature requests, please use the <a href="https://github.com/kent-tokyo/plactice_math/issues" target="_blank" rel="noopener noreferrer">GitHub Issues</a> page.
          </p>
        </div>
      </main>
      <Footer />
    </div>
  );
}
